#
# Copyright 2021 ABSA Group Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: License Check

on:
  workflow_call:
    inputs:
      jave_version:
        description: 'Java version to be used by setup-java action'
        default: '1.8'
        required: false
        type: string
      jave_distribution:
        description: 'Java distribution to be used by setup-java action'
        default: 'adopt'
        required: false
        type: string


jobs:
  license-test:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: ${{ inputs.jave_distribution }}
          java-version: ${{ inputs.jave_version }}
      - run: mvn --no-transfer-progress -Plicense-check apache-rat:check
